"""Render a fleet workspace into a runnable deploy tree.

`a2y render` reads fleet.yaml + agents/*/agent.yaml and writes `deploy/`:

    deploy/docker-compose.yaml      one service per agent
    deploy/example.env              every variable the compose file references
    deploy/agents/<name>/           the /config directory mounted into the agent:
        agent.yaml                  identity + ports (read by the entrypoint)
        SOUL.md                     persona + fleet-shared section
        config.yaml                 Hermes
        acp2api.yaml                the ACP bridge and its MCP servers
        litellm.yaml                the failover chain
        hindsight.json              memory profile (when memory is hindsight)
    deploy/banks/*.json             shared bank profiles, copied

The output is deterministic: same manifests, same tree, byte for byte. Commit it —
a reviewable deploy tree is the point of generating instead of hand-writing.

Escape hatch: agents/<name>/overrides/<filename> replaces the generated file
verbatim. Use it when a knob the generator does not expose is needed; prefer
teaching the generator when the need repeats.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml

from .manifest import Agent, Fleet, ManifestError

GENERATED = "# GENERATED by `a2y render` -- edit the manifests, not this file.\n"

# Hermes toolsets that stay off in every agent: third-party keys this pack does
# not assume, surfaces a channel-resident agent has no use for, and everything
# the coding CLI already does better in its own loop (a duplicate is not free --
# every Hermes-side call ends the completion and round-trips through Hermes).
DISABLED_TOOLSETS = [
    "bfl", "browser", "code_execution", "computer_use", "desktop_ui",
    "discord", "discord_admin", "feishu_doc", "feishu_drive", "file",
    "homeassistant", "image_gen", "search", "spotify", "stt", "terminal",
    "todo", "tts", "video", "video_gen", "vision", "web", "x_search", "yuanbao",
]

MATTERMOST_PLUGINS = [
    "mention-on-edit",   # a mention arriving by EDIT wakes nobody upstream
    "untagged-routing",  # exactly one agent claims an untagged human message
    "trace-to-card",     # answer in the post, working trace behind the (i) card
    "reasoning-live",    # live progress bubble while a turn runs
    "steer-into-turn",   # /steer lands INSIDE the running ACP turn
]


def _dump(data: dict, header: str = GENERATED) -> str:
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)


def _executor_entry(name: str, spec: dict, mcp: list[dict]) -> dict:
    """One entry in acp2api's `agents:` list."""
    kind = spec.get("kind") or name
    entry: dict = {"name": name}
    if kind == "claude":
        entry["type"] = "claude"
        # bypassPermissions is refused under root without IS_SANDBOX=1, and the
        # containers run as root; acceptEdits costs nothing on top of
        # `permission: allow` and does not fail at session setup.
        entry["mode"] = spec.get("mode", "acceptEdits")
    elif kind == "codex":
        entry["type"] = "codex"
        # codex-acp sends a sandboxPolicy per TURN from the ACP session mode;
        # bubblewrap cannot work inside these containers, so the default mode
        # costs a failed first attempt on every command. config.toml does not fix
        # this; the session mode does.
        entry["mode"] = spec.get("mode", "agent-full-access")
    elif kind == "opencode":
        entry["type"] = "general"
        entry["command"] = "opencode"
        entry["args"] = ["acp"]
    elif kind == "cline":
        entry["type"] = "general"
        entry["command"] = "cline"
        entry["args"] = ["--acp"]
    elif kind == "custom":
        entry["type"] = "general"
        entry["command"] = spec["command"]
        if spec.get("args"):
            entry["args"] = list(spec["args"])
    if spec.get("model"):
        entry["model"] = spec["model"]
    if spec.get("reasoning"):
        entry["reasoning"] = spec["reasoning"]
    if spec.get("env"):
        entry["env"] = dict(spec["env"])
    if spec.get("account"):
        # Which subscription this executor spends. Declared, not discovered: it
        # is a property of the login volume, and no ACP message reports it.
        entry["labels"] = {"account": spec["account"]}
    entry["mcpServers"] = mcp
    return entry


def _mcp_servers(agent: Agent) -> list[dict]:
    """The default MCP set for one agent, plus its manifest extras.

    These go in acp2api.yaml, INSIDE the ACP session -- the cheap route. Tools
    routed through Hermes' `tools` array end the completion on every call.
    """
    fleet = agent.fleet
    servers: list[dict] = [
        {
            # Hermes' own bridge: read-only cross-thread history, skills, events.
            # stdio only; finds $HERMES_HOME from $HOME on its own.
            "name": "hermes",
            "type": "stdio",
            "command": "/opt/agent/hermes-agent/venv/bin/hermes",
            "args": ["mcp", "serve"],
        }
    ]
    if fleet.platform_kind == "mattermost":
        for tool in ("boards", "playbooks"):
            if agent.raw.get("tools", {}).get(tool, True):
                servers.append({
                    # A stdio sidecar reusing THIS container's MATTERMOST_TOKEN:
                    # the agent's reach is exactly its own account's reach.
                    "name": tool,
                    "type": "stdio",
                    "command": f"mattermost-{tool}-mcp",
                    "args": ["--url", "${MATTERMOST_URL}", "--token", "${MATTERMOST_TOKEN}",
                             "--team", "${MATTERMOST_TEAM}"],
                })
    if fleet.memory_kind == "hindsight":
        url = str(fleet.memory["url"]).rstrip("/")
        if agent.memory.get("personal", True):
            servers.append({
                "name": "memory-own",
                "url": f"{url}/mcp/agent-{agent.name}/",
                "headers": {"Authorization": "Bearer ${HINDSIGHT_API_KEY}"},
            })
        for project in agent.project_banks():
            servers.append({
                # Shared bank: tools-only on purpose -- a bank several agents
                # read should be written deliberately, not as a side effect.
                "name": f"memory-{project}",
                "url": f"{url}/mcp/project-{project}/",
                "headers": {"Authorization": "Bearer ${HINDSIGHT_API_KEY}"},
            })
    if fleet.observability.get("phoenix_url"):
        servers.append({
            # The fleet's own traces as tools. Command is `phoenix-mcp` (npm
            # strips the scope); the URL goes in as a flag because the package
            # reads several env names. No `env:` here on purpose -- ACP `env`
            # REPLACES the child environment and node vanishes from PATH.
            "name": "traces",
            "type": "stdio",
            "command": "phoenix-mcp",
            "args": ["--baseUrl", "${PHOENIX_URL}"],
        })
    servers.extend(agent.extra_mcp)
    return servers


def render_acp2api(agent: Agent) -> str:
    ports = agent.ports()
    server = {
        "host": "127.0.0.1",
        "port": "${ACP2API_PORT}",
        # Set by the entrypoint: a fixed bind in bridge mode, a discovered one in
        # shared-namespace mode, "off" when nothing scrapes.
        "metricsAddr": "${ACP2API_METRICS_ADDR:-off}",
        "cwd": "/work",
        "fs": True,
        "terminal": False,       # advertised-but-ignored by Claude Code; measured
        "permission": "allow",   # nobody is at a keyboard; /work bounds the blast radius
        "progress": "reasoning",
        "progressOutputLines": 6,
        "commentary": "trace",
        "busy": "queue",         # lets a steered message join the RUNNING turn
        "requestTimeoutMs": 900000,
        "continuity": True,
        "maxSessions": 20,
        "sessionTtlMs": 1800000,
        "forgetTtlMs": 86400000,
        "maxContextFill": 0.85,
    }
    server.update(agent.raw.get("acp2api") or {})
    _ = ports  # ports land in agent.yaml; acp2api reads its own from the env
    mcp = _mcp_servers(agent)
    agents = [_executor_entry(n, agent.executors[n], mcp) for n in agent.chain
              if (agent.executors[n].get("kind") or n) != "openai"]
    return _dump({"server": server, "agents": agents})


def render_litellm(agent: Agent) -> str:
    model_list = []
    fallback_names = []
    for i, name in enumerate(agent.chain):
        spec = agent.executors[name]
        kind = spec.get("kind") or name
        model_name = "brain" if i == 0 else f"brain-{name}"
        fallback_names.append(model_name)
        if kind == "openai":
            params = {
                "model": f"openai/{spec.get('model', 'default')}",
                "api_base": spec["base_url"],
                "api_key": f"os.environ/{spec.get('api_key_env', 'OPENAI_API_KEY')}",
                "timeout": 900,
            }
        else:
            params = {
                "model": f"openai/{name}",
                "api_base": "os.environ/ACP2API_BASE_URL",
                # acp2api has no auth (loopback); litellm still wants a word.
                "api_key": "none-required",
                "timeout": 900,
                # An ACP agent answers in prose; response_format 400s. Hermes
                # sends it for titling, so it must be dropped by name here.
                "additional_drop_params": ["response_format"],
            }
        model_list.append({"model_name": model_name, "litellm_params": params})
    data = {
        "model_list": model_list,
        "litellm_settings": {
            # Absorb params the transport cannot carry (reasoning_effort et al).
            "drop_params": True,
            # 429 from acp2api means a SPENT subscription -- retrying the same
            # model burns time to reach the same answer; the chain is the retry.
            "num_retries": 0,
            "request_timeout": 900,
            "cache": False,
        },
        "general_settings": {
            "master_key": "os.environ/LITELLM_MASTER_KEY",
            # Without this the x-conversation-id header dies here and every
            # message opens a COLD coding agent.
            "forward_client_headers_to_llm_api": True,
        },
    }
    if len(fallback_names) > 1:
        data["litellm_settings"]["fallbacks"] = [{"brain": fallback_names[1:]}]
    return _dump(data)


def render_hermes_config(agent: Agent) -> str:
    fleet = agent.fleet
    plugins = ["conversation-key"]
    if fleet.platform_kind == "mattermost":
        plugins += MATTERMOST_PLUGINS
    if fleet.observability.get("phoenix_url"):
        plugins.append("hermes_otel")

    data: dict = {
        "model": {
            "provider": "custom",
            "default": "brain",
            "base_url": "${LITELLM_BASE_URL}",
            # MUST be explicit: `provider: custom` does not fall back to
            # OPENAI_API_KEY -- Hermes sends the literal `no-key-required` and
            # litellm reports it as "No connected db.", which reads as a broken
            # proxy rather than bad auth.
            "api_key": "${LITELLM_MASTER_KEY}",
        },
        "agent": {
            "max_turns": 90,
            "verbose": False,
            "disabled_toolsets": list(DISABLED_TOOLSETS),
        },
        "terminal": {"backend": "local", "cwd": "/work", "timeout": 600},
        "group_sessions_per_user": False,
        "session_reset": {"mode": "none"},
        "compression": {"enabled": False},
        "streaming": {"enabled": False},
        "display": {
            "busy_input_mode": "steer",
            "show_reasoning": True,
            "reasoning_style": "blockquote",
            "tool_progress_grouping": "accumulate",
            "cleanup_progress": True,
        },
        "onboarding": {"seen": {"busy_input_prompt": True, "tool_progress_prompt": True}},
        "auxiliary": {"title_generation": {"enabled": False}},
        "gateway": {"platforms": {"a2a": {"enabled": True}}},
        "plugins": {"enabled": plugins},
        "telemetry": {"shared_metrics": {"enabled": False}},
    }
    if fleet.platform_kind == "mattermost":
        data["platform_toolsets"] = {"mattermost": ["hermes-mattermost"]}
        # Three display settings are DISCARDED on Mattermost unless the platform
        # repeats them (require_platform_override_for) -- silently, with the
        # top-level value still sitting in the file looking correct.
        data["display"]["platforms"] = {
            "mattermost": {"show_reasoning": True, "thinking_progress": True}
        }
    if fleet.memory_kind == "hindsight" and agent.memory.get("personal", True):
        data["memory"] = {
            "provider": "hindsight",
            "memory_enabled": True,
            "user_profile_enabled": True,
        }
    hermes_over = agent.raw.get("hermes") or {}
    if hermes_over:
        from .manifest import _deep_merge  # local import to keep module API small
        data = _deep_merge(data, hermes_over)
    return _dump(data)


def render_agent_yaml(agent: Agent) -> str:
    """The runtime identity file the entrypoint reads (and /fleet roster scans)."""
    ports = agent.ports()
    data: dict = {
        "name": agent.name,
        "description": agent.description,
        "ports": {"acp2api": ports["acp2api"], "litellm": ports["litellm"], "a2a": ports["a2a"]},
    }
    if agent.fleet.platform_kind == "mattermost":
        data["mattermost"] = {
            "reply_mode": agent.platform.get("reply_mode", "thread"),
            "require_mention": agent.platform.get("require_mention", True),
        }
    if agent.fleet.memory_kind == "hindsight":
        data["memory"] = {"mode": "local_external", "url": agent.fleet.memory["url"]}
    return _dump(data)


DEFAULT_RETAIN_MISSION = (
    "Keep durable facts about this work and how the operator wants it run. Skip transient "
    "state -- ids, one-off command output, anything that stops being true when the task ends. "
    "Extract the FEWEST facts that capture the OUTCOME: settled DECISIONS and their exact "
    "rules/values (quote literals VERBATIM); problems and how they were resolved; conventions "
    "established. CRITICAL: a conversation REVISES itself -- record ONLY the FINAL state as "
    "what is in effect. NEVER record what the AGENT did, offered, confirmed or will do next. "
    "Record what the OPERATOR wants, decides and repeats. NEVER record general knowledge, "
    "definitions, or explanations."
)

DEFAULT_OBSERVATIONS_MISSION = (
    "Consolidate durable knowledge -- recurring patterns, conventions, responsibilities, and "
    "how components relate. Favor stable structural understanding over one-off details. When a "
    "new fact contradicts or supersedes an existing observation, UPDATE that observation to "
    "reflect the current state rather than creating a sibling; note that the rule was revised "
    "and when. NEVER record what the AGENT did. NEVER record measurements or system state. "
    "NEVER record general knowledge."
)


def render_hindsight(agent: Agent) -> str:
    mem = agent.memory
    data = {
        "mode": "local_external",
        "api_url": agent.fleet.memory["url"],
        "bank_id": f"agent-{agent.name}",
        "bank_mission": mem.get(
            "mission",
            f"The working memory of {agent.name}: {agent.description} What matters: decisions "
            "and the reasoning behind them, what has broken before and why, and the operator's "
            "standing preferences.",
        ),
        "bank_retain_mission": mem.get("retain_mission", DEFAULT_RETAIN_MISSION),
        "bank_observations_mission": mem.get("observations_mission", DEFAULT_OBSERVATIONS_MISSION),
        # `context` keeps automatic injection and drops the duplicate tools --
        # the MCP banks in acp2api.yaml are the deliberate-write route.
        "memory_mode": "context",
        "auto_recall": True,
        "recall_budget": "mid",
        "recall_max_tokens": 4096,
        "auto_retain": mem.get("auto_retain", True),
        "retain_async": True,
        "retain_every_n_turns": 1,
        "retain_context": mem.get(
            "retain_context",
            f"work in a chat channel between the operator and the {agent.name} agent",
        ),
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# compose + env
# ---------------------------------------------------------------------------

def _agent_service(agent: Agent) -> dict:
    fleet = agent.fleet
    p = agent.env_prefix
    env: dict[str, str] = {
        # Claude Code splits state between ~/.claude and ~/.claude.json; without
        # this a container replacement loses the account while appearing not to.
        "CLAUDE_CONFIG_DIR": "/root/.claude",
        "LITELLM_MASTER_KEY": f"${{{p}_LITELLM_MASTER_KEY}}",
        # Where Hermes looks for its bearer when model.base_url is set. Never a
        # real provider key -- a real one here would let codex quietly bill an
        # API account instead of spending the subscription.
        "OPENAI_API_KEY": f"${{{p}_LITELLM_MASTER_KEY}}",
        # cline reinstalls itself from `latest` at startup, defeating the image
        # pin and briefly deleting its own binary. This stops it.
        "CLINE_NO_AUTO_UPDATE": "1",
    }
    if fleet.platform_kind == "mattermost":
        env.update({
            "MATTERMOST_URL": "${A2Y_MATTERMOST_URL}",
            "MATTERMOST_TOKEN": f"${{{p}_MATTERMOST_TOKEN}}",
            "MATTERMOST_TEAM": "${A2Y_MATTERMOST_TEAM}",
            # ONE list for the whole fleet: every human and every agent id. A
            # message from an id not here is dropped before anything looks at
            # it, with no error anywhere. Changing it means recreating agents.
            "MATTERMOST_ALLOWED_USERS": "${A2Y_MATTERMOST_ALLOWED_USERS}",
            # Which of those ids are PEOPLE -- the untagged-routing loop guard.
            "MATTERMOST_HUMANS": "${A2Y_MATTERMOST_HUMANS}",
            # room:agent map for untagged messages; same value for every agent.
            "AGENT_ROOM_OWNERS": "${A2Y_ROOM_OWNERS}",
            # Keep empty unless you need a second fence: membership already
            # limits delivery, and this one drops group DMs in silence.
            "MATTERMOST_ALLOWED_CHANNELS": f"${{{p}_MATTERMOST_CHANNELS}}",
            "MATTERMOST_HOME_CHANNEL": f"${{{p}_MATTERMOST_HOME_CHANNEL}}",
        })
    if fleet.memory_kind == "hindsight":
        env["HINDSIGHT_API_KEY"] = "${A2Y_HINDSIGHT_API_KEY}"
    phoenix = fleet.observability.get("phoenix_url")
    if phoenix:
        env["PHOENIX_URL"] = "${A2Y_PHOENIX_URL}"
        env["OTEL_PHOENIX_ENDPOINT"] = "${A2Y_PHOENIX_URL}/v1/traces"
        # One Phoenix project per agent: "whose tokens" stays answerable.
        env["OTEL_PROJECT_NAME"] = agent.container
    if fleet.observability.get("prometheus"):
        env["A2Y_METRICS_BIND"] = "0.0.0.0" if not fleet.shared_namespace else ""
        if fleet.shared_namespace:
            env["A2Y_METRICS_PROBE_HOST"] = str(fleet.observability.get("probe_host") or "")
    if agent.access.get("github_token"):
        env["GH_TOKEN"] = f"${{{p}_GH_TOKEN}}"
    if fleet.shared_namespace:
        env["A2Y_SHARED_NAMESPACE"] = "1"
        env["AGENT_VPN_IFACE"] = str(fleet.network.get("iface") or "")
        env["A2Y_PEER_ADDR_TEMPLATE"] = "http://127.0.0.1:{a2a}/"
    # Free-form passthrough, fleet-level then agent-level.
    for extra in (fleet.platform.get("env") or {}, agent.raw.get("env") or {}):
        for k, v in extra.items():
            env[str(k)] = str(v)
    env = {k: v for k, v in env.items() if v != ""}

    volumes = [
        f"./agents/{agent.name}:/config:ro",
        # The whole fleet's identity, read-only: the roster generator reads every
        # peer's agent.yaml from here, so nobody describes a colleague by hand.
        "./agents:/fleet:ro",
    ]
    if (fleet.root / "banks").is_dir():
        volumes.append("./banks:/banks:ro")
    state = f"../volumes/{agent.container}"
    # The logins are the only state that cannot be rebuilt from the repository;
    # an image rebuild must never sign an agent out.
    for sub, target in [
        ("claude", "/root/.claude"), ("codex", "/root/.codex"),
        ("opencode", "/root/.config/opencode"), ("cline", "/root/.cline"),
        ("gh", "/root/.config/gh"), ("tea", "/root/.config/tea"),
        ("hermes", "/root/.hermes"),
    ]:
        volumes.append(f"{state}/{sub}:{target}")
    if agent.access.get("ssh"):
        volumes.append(f"{state}/ssh:/root/.ssh")
    volumes.append(f"{state}/workspace:/work")

    service: dict = {
        "container_name": agent.container,
        "image": "${A2Y_IMAGE}",
        "restart": "unless-stopped",
        # On SIGTERM the gateway finishes its turn; behind it a coding CLI may be
        # mid-edit. Killing at 10s loses work.
        "stop_grace_period": "60s",
        "environment": [f"{k}={v}" for k, v in env.items()],
        "volumes": volumes,
        "healthcheck": {
            # litellm's liveness: the only probe that is both unauthenticated and
            # meaningless to fake. acp2api shows up here as a failed request.
            "test": ["CMD-SHELL",
                     ". /run/agent.env && curl -fsS http://127.0.0.1:$$LITELLM_PORT/health/liveliness || exit 1"],
            "interval": "30s",
            "timeout": "10s",
            "retries": 3,
            "start_period": "120s",
        },
    }
    if fleet.shared_namespace:
        # Cross-file namespace sharing: `container:`, not `service:`. Do NOT add
        # networks: or ports: -- both conflict with network_mode.
        service["network_mode"] = fleet.network_mode
    else:
        service["networks"] = ["a2y"]
    return service


def render_compose(fleet: Fleet) -> str:
    data: dict = {"services": {a.container: _agent_service(a) for a in fleet.agents}}
    if not fleet.shared_namespace:
        data["networks"] = {"a2y": {"name": f"{fleet.name}_net"}}
    header = (
        GENERATED
        + "#\n# One service per agent; the image is built once (`a2y build`) and\n"
        "# instantiated per agent. Secrets come from .env next to this file.\n"
    )
    return _dump(data, header)


def render_example_env(fleet: Fleet) -> str:
    lines = [
        "# Copy to `.env` next to docker-compose.yaml and fill in.",
        "#",
        "# INVARIANT: .env must never fall below this file's variable set. A missing",
        "# variable can make an UNRELATED service's compose fail to render.",
        "",
        "# The agent image, built by `a2y build`.",
        f"A2Y_IMAGE={fleet.image_tag}",
        "",
    ]
    if fleet.platform_kind == "mattermost":
        lines += [
            "# --- Mattermost (see docs/provisioning.md for the account sequence) ---",
            "A2Y_MATTERMOST_URL=http://your-mattermost:8065",
            f"A2Y_MATTERMOST_TEAM={fleet.platform.get('team', 'yourteam')}",
            "# Every human and every agent USER ID, comma-separated. A sender not on",
            "# this list is dropped in silence, delegation included.",
            "A2Y_MATTERMOST_ALLOWED_USERS=",
            "# The subset of those ids that are PEOPLE (untagged-routing loop guard).",
            "A2Y_MATTERMOST_HUMANS=",
            "# room:agent map for untagged messages, e.g. `default:ana,project-x:pm`.",
            "A2Y_ROOM_OWNERS=",
            "",
        ]
    if fleet.memory_kind == "hindsight":
        lines += [
            "# --- Memory (Hindsight) ---",
            "A2Y_HINDSIGHT_API_KEY=",
            "",
        ]
    if fleet.observability.get("phoenix_url"):
        lines += [
            "# --- Observability ---",
            f"A2Y_PHOENIX_URL={fleet.observability['phoenix_url']}",
            "",
        ]
    for a in fleet.agents:
        p = a.env_prefix
        lines.append(f"# --- {a.name} ---")
        lines.append(f"# Internal bearer between Hermes -> litellm -> acp2api. Not a provider key.")
        lines.append(f"{p}_LITELLM_MASTER_KEY=")
        if fleet.platform_kind == "mattermost":
            lines.append(f"{p}_MATTERMOST_TOKEN=")
            lines.append(f"# Channel the agent posts to UNPROMPTED (cron, alerts). Exactly one.")
            lines.append(f"{p}_MATTERMOST_HOME_CHANNEL=")
            lines.append(f"# Extra inbound fence; keep empty unless you know why (drops group DMs).")
            lines.append(f"{p}_MATTERMOST_CHANNELS=")
        if a.access.get("github_token"):
            lines.append(f"# Fine-grained PAT scoped to the repositories this agent owns.")
            lines.append(f"{p}_GH_TOKEN=")
        lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# the render pass
# ---------------------------------------------------------------------------

def _write(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def _soul(agent: Agent) -> str:
    soul = (agent.dir / "SOUL.md").read_text().rstrip("\n") + "\n"
    shared = agent.fleet.root / "SOUL-shared.md"
    if shared.is_file():
        soul += "\n" + shared.read_text().rstrip("\n") + "\n"
    return soul


def render_fleet(fleet: Fleet, out: Path | None = None) -> list[str]:
    """Write the deploy tree; returns the paths that changed."""
    out = out or (fleet.root / "deploy")
    changed: list[str] = []

    def emit(rel: str, content: str) -> None:
        if _write(out / rel, content):
            changed.append(rel)

    for agent in fleet.agents:
        files = {
            "agent.yaml": render_agent_yaml(agent),
            "SOUL.md": _soul(agent),
            "config.yaml": render_hermes_config(agent),
            "acp2api.yaml": render_acp2api(agent),
            "litellm.yaml": render_litellm(agent),
        }
        if fleet.memory_kind == "hindsight" and agent.memory.get("personal", True):
            files["hindsight.json"] = render_hindsight(agent)
        overrides = agent.dir / "overrides"
        for fname, content in files.items():
            override = overrides / fname
            if override.is_file():
                content = override.read_text()
            emit(f"agents/{agent.name}/{fname}", content)

    banks = fleet.root / "banks"
    if banks.is_dir():
        for f in sorted(banks.glob("*.json")):
            emit(f"banks/{f.name}", f.read_text())

    emit("docker-compose.yaml", render_compose(fleet))
    emit("example.env", render_example_env(fleet))
    return changed


def ensure_volumes(fleet: Fleet) -> list[Path]:
    """Create the per-agent state directories compose bind-mounts. Called by
    `a2y up` so a fresh checkout starts without a .gitkeep ritual. Markers stop
    at the service directory on purpose -- containers own everything below."""
    created = []
    for agent in fleet.agents:
        base = fleet.root / "volumes" / agent.container
        subs = ["claude", "codex", "opencode", "cline", "gh", "tea", "hermes", "workspace"]
        if agent.access.get("ssh"):
            subs.append("ssh")
        for sub in subs:
            d = base / sub
            if not d.is_dir():
                d.mkdir(parents=True, exist_ok=True)
                created.append(d)
    return created


def clean(fleet: Fleet) -> None:
    shutil.rmtree(fleet.root / "deploy", ignore_errors=True)
