#!/opt/agent/hermes-agent/venv/bin/python3
"""Write the fleet roster into the agent's runtime SOUL.md.

WHY. "Read your colleagues' Agent Cards" is right about staleness and expensive
in practice: learning who does what costs thousands of tokens and several tool
round-trips to obtain a couple of hundred tokens of fact -- per agent, per time.

The roster is not maintained by hand. It is generated from every peer's own
`agent.yaml` -- the same fields their Agent Card is built from -- so it cannot
disagree with the cards, and no repository SOUL.md ever names a colleague.

WHY A LOOP AND NOT ONLY START-UP. A new agent must not need the rest of the
fleet restarted to be found: /fleet is a bind mount, so a re-render on the host
is visible inside every running container at once, and Hermes re-reads SOUL.md
once per SESSION -- so the next conversation picks the rewrite up for free.

Rebuilt from the pristine SOUL.md each time (idempotent), written only when the
result differs.

Peer addresses: A2Y_PEER_ADDR_TEMPLATE, with {name} and {a2a} placeholders
(e.g. `http://127.0.0.1:{a2a}/` on a shared namespace). Unset means the fleet's
A2A cards are not cross-reachable -- the roster then lists who exists without an
address, and exchanges go through the chat platform, which is where they belong
anyway.

Usage: fleet-roster.py <fleet-dir> <source-SOUL.md> <target-SOUL.md> <own-name>
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import yaml

# Past this many peers a flat list in every prompt stops being the cheap option
# and the right answer becomes a search service. Nothing breaks at the
# threshold; it prints, so the decision is prompted by evidence.
ROSTER_SOFT_LIMIT = 40

MARKER = "<!-- fleet roster: generated by fleet-roster.py"


def collect(fleet_dir: Path, me: str) -> list[tuple[str, str, str]]:
    """(name, description, address) for every agent in the fleet except this one."""
    template = os.environ.get("A2Y_PEER_ADDR_TEMPLATE", "")
    peers: list[tuple[str, str, str]] = []
    for path in sorted(fleet_dir.glob("*/agent.yaml")):
        try:
            cfg = yaml.safe_load(path.read_text()) or {}
        except Exception as exc:  # a peer's broken yaml is not this agent's problem
            print(f"  skipped {path}: {exc}", file=sys.stderr)
            continue
        name = str(cfg.get("name") or path.parent.name).strip()
        if name == me:
            continue
        desc = " ".join(str(cfg.get("description") or "").split())
        if os.environ.get("A2Y_ROSTER_MODE", "full") == "brief":
            desc = desc.split(".", 1)[0].strip() + ("." if "." in desc else "")
        if not desc:
            continue
        port = (cfg.get("ports") or {}).get("a2a")
        addr = template.format(name=name, a2a=port) if (template and port) else ""
        peers.append((name, desc, addr))
    return peers


def render(peers: list[tuple[str, str, str]]) -> str:
    if os.environ.get("A2Y_ROSTER_MODE", "full") == "off":
        return ""
    lines = [
        "",
        MARKER + " from every agent.yaml in the fleet.",
        "     Edits here are overwritten; change the peer's own agent.yaml, which",
        "     is also what its Agent Card is built from. -->",
        "",
        "## The colleagues you have",
        "",
    ]
    if not peers:
        lines.append("None are configured.")
        return "\n".join(lines) + "\n"

    for name, desc, addr in peers:
        suffix = f" ({addr})" if addr else ""
        lines.append(f"- **{name}**{suffix} — {desc}")
    lines += [
        "",
        "Generated from the same field each Agent Card publishes, and refreshed",
        "while this agent runs -- a colleague added since it started appears here",
        "without anybody being restarted. Use it instead of reading cards to find",
        "out who does what. Reach a colleague with an @mention in the channel;",
        "delivery only happens in channels you are BOTH members of.",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 5:
        print(__doc__, file=sys.stderr)
        return 2
    fleet_dir, source, target, me = Path(argv[1]), Path(argv[2]), Path(argv[3]), argv[4]

    if not fleet_dir.is_dir() or not source.is_file():
        # Not an error: an agent deployed without the fleet mount keeps the
        # SOUL.md it was given.
        return 0

    peers = collect(fleet_dir, me)
    tier = os.environ.get("A2Y_DIARIZATION_TIER", "")
    model_manifest = Path("/models/manifest.json")
    if not tier and model_manifest.is_file():
        try:
            tier = str(__import__("json").loads(model_manifest.read_text()).get("tier") or "")
        except (OSError, ValueError):
            tier = ""
    identity = source.read_text().replace("{{A2Y_DIARIZATION_TIER}}", tier or "models-not-pulled")
    wanted = identity.rstrip("\n") + "\n" + render(peers)

    if target.is_file() and target.read_text() == wanted:
        return 0

    target.write_text(wanted)
    print(f"  roster: {len(peers)} peer(s): {', '.join(n for n, _, _ in peers) or '-'}")
    if len(peers) > ROSTER_SOFT_LIMIT:
        print(
            f"  roster is past {ROSTER_SOFT_LIMIT} peers -- a flat list in every "
            "prompt is no longer the cheap option",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
